# Generated by Django 5.1.5 on 2025-01-30 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthCare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('TECHNICIAN', 'Technician'), ('RECEPTIONIST', 'Receptionist'), ('SUPPORT_STAFF', 'Support Staff'), ('PHARMACIST', 'Pharmacist'), ('HOSPITAL', 'Hospital'), ('ADMIN', 'Admin')], default='PATIENT', max_length=20),
        ),
    ]
